# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        oauth_token:
            pattern:    ^/oauth/v2/token
            security:   false

        #oauth_authorize:
            #pattern:    ^/oauth/v2/auth
            #form_login:
                #check_path: fos_user_security_check
                #login_path: fos_user_security_login
            #anonymous: true

        public:
            pattern:    ^/public
            security:   false

        api:
            pattern:    ^/
            fos_oauth:  true
            stateless:  true
            anonymous:  true # can be omitted as its default value

    access_control:
        - { path: ^/api/v[0-9]+/public*, roles: [ IS_AUTHENTICATED_ANONYMOUSLY ] }
        - { path: ^/api/v[0-9]+/activity*, roles: [ ROLE_USER ] }
        - { path: ^/api/v[0-9]+/user*, roles: [ ROLE_USER ] }
