# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
imports:
    - { resource: custom_parameters.yml }

parameters:
#    parameter_name: value

services:
#    service_name:
#        class: ActivisMap\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

  api_exception_subscriber:
      class: ActivisMap\Error\ExceptionSubscriber
      arguments: []
      tags:
          - { name: kernel.event_subscriber }

  websocket_service:
      class: ActivisMap\Util\WebSocket\SocketTopic
      arguments:
        - '@doctrine.orm.entity_manager'
        - '@gos_web_socket.zmq.pusher'
      tags:
        - { name: gos_web_socket.rpc }

  gos_web_socket_server.client_event.listener:
      class: ActivisMap\Util\WebSocket\ClientListener
      arguments:
        - '@doctrine.orm.entity_manager'
      tags:
          - { name: kernel.event_listener, event: 'gos_web_socket.client_connected', method: onClientConnect }
          - { name: kernel.event_listener, event: 'gos_web_socket.client_disconnected', method: onClientDisconnect }
          - { name: kernel.event_listener, event: 'gos_web_socket.client_error', method: onClientError }
          - { name: kernel.event_listener, event: 'gos_web_socket.server_launched', method: onServerStart }
          - { name: kernel.event_listener, event: 'gos_web_socket.client_rejected', method: onClientRejected }