# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
imports:
    - { resource: custom_parameters.yml }

parameters:
#    parameter_name: value

services:
#    service_name:
#        class: ActivisMap\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

  api_exception_subscriber:
      class: ActivisMap\Error\ExceptionSubscriber
      arguments: []
      tags:
          - { name: kernel.event_subscriber }